workflows:
  android-workflow:
    name: NoConfuse Android APK
    max_build_duration: 30
    environment:
      flutter: stable
    scripts:
      - name: Set up Flutter project files
        script: |
          cd noconfuse_app
          flutter create . --platforms=android --org com.noconfuse
      - name: Get Flutter packages
        script: |
          cd noconfuse_app
          flutter pub get
      - name: Build APK
        script: |
          cd noconfuse_app
          flutter build apk --release
    artifacts:
      - noconfuse_app/build/app/outputs/flutter-apk/app-release.apk
